on:
  release:
    types: [created]

name: Upload release assets after release is created
jobs:
  build:
    name: build binaries
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          echo "GO111MODULE=on" >> $GITHUB_ENV
          GOOS=windows GOARCH=amd64 go build -o bin/windows/krv.exe
          GOOS=linux   GOARCH=amd64 go build -o bin/linux/krv
          GOOS=linux   GOARCH=arm64 go build -o bin/linux_arm/krv
          GOOS=darwin  GOARCH=amd64 go build -o bin/darwin/krv
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/

  upload:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v1

      - name: Download build artefacts
        uses: actions/download-artifact@v1
        with:
          name: binaries
          path: bin/

      - name: Create asset zips
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        run: |
          mkdir assets
          zip assets/krv-${SOURCE_TAG}-windows-amd64.zip bin/windows/krv.exe README.md
          zip assets/krv-${SOURCE_TAG}-linux-amd64.zip bin/linux/krv README.md
          zip assets/krv-${SOURCE_TAG}-linux-arm64.zip bin/linux_arm/krv README.md
          zip assets/krv-${SOURCE_TAG}-darwin-amd64.zip bin/darwin/krv README.md
          sha256sum assets/*zip > assets/SHASUMS256.txt
      - name: Upload release assets
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './assets/*'
